### ISSUE TITLE
Attacking while on vehicle bug

### ISSUE THREAD

**Issue by Frizy0** [OpenFusionProject/OpenFusion#49] opened 2020-08-26 20:13 UTC
Attacking while on vehicle makes the getting off animation played several times as well as the audio.
Source: https://www.youtube.com/watch?v=Ywq11s9v8sE

**Comment by CakeLancelot** [comment] 2020-08-26 20:30
We should probably also send a fail packet when the player doesn't have a vehicle - currently it plays the sound as if you were getting on the vehicle but nothing happens.

**Comment by CakeLancelot** [comment] 2020-08-28 18:22
Seems to be fixed with #51?

**Comment by Frizy0** [comment] 2020-08-28 18:25
> Seems to be fixed with #51?

Still present for me, just tried.

**Comment by CakeLancelot** [comment] 2020-08-28 18:37
That's weird, it works fine on a local server. I'll look into this further later on

**Comment by CakeLancelot** [comment] 2020-09-19 13:01
The cause of this is the client sending multiple ``P_CL2FE_REQ_PC_VEHICLE_OFF``, but only when attacking for whatever reason. It's less noticeable on a local server, since there's little to no latency. The fix is probably to only send a ``VEHICLE_OFF_SUCC`` after the last received ``VEHICLE_OFF`` packet, or to implement some sort of cooldown.

**Comment by CakeLancelot** [comment] 2020-10-28 21:19
Should be fixed when #143 is merged.

**Closed** 2020-10-31 18:24 UTC
Labels: bug
